# .golangci.yml
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - bodyclose
    - misspell
    - unconvert
    - unparam
    - gocritic
    - exhaustive
    - copyloopvar # Useful for Go 1.22+; checks for correct variable capture in loops.

linters-settings:
  gosec:
    severity: medium
    confidence: medium
  revive:
    rules:
      - name: exported
        severity: warning
      - name: blank-imports
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0