modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: ChaosChain
      pre_blockers: [upgrade, auth, bank, staking, distribution, slashing, gov, genutil, feemarket, penalty]
      begin_blockers: [mint, distribution, slashing, staking, bank]
      end_blockers: [staking, bank, gov, feemarket]
      init_genesis: [auth, bank, staking, mint, distribution, slashing, gov, upgrade, genutil, feemarket, penalty]
      export_genesis: [auth, bank, staking, mint, distribution, slashing, gov, upgrade, genutil, feemarket, penalty]
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: chaos
      module_account_permissions:
        - account: bonded_tokens_pool
          permissions: [burner, staking]
        - account: not_bonded_tokens_pool
          permissions: [burner, staking]
        - account: distribution
          permissions: []
        - account: gov
          permissions: []
        - account: mint
          permissions: [minter]
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
  - name: distribution
    config:
      "@type": cosmos.distribution.module.v1.Module
  - name: gov
    config:
      "@type": cosmos.gov.module.v1.Module
  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
      hooks_order: [distribution, slashing]
  - name: slashing
    config:
      "@type": cosmos.slashing.module.v1.Module
  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
