modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: ChaosChain
      begin_blockers: [staking, bank]
      end_blockers: [staking, bank, feemarket]
      init_genesis: [auth, bank, staking, feemarket, slashing]
      export_genesis: [auth, bank, staking, feemarket, slashing]
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: chaos
      module_account_permissions:
        - account: bonded_tokens_pool
          permissions: [burner, staking]
        - account: not_bonded_tokens_pool
          permissions: [burner, staking]
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
